# Generated by Django 2.1 on 2019-04-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190421_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_name',
            new_name='title',
        ),
    ]
