# Generated by Django 2.1 on 2019-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190421_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(null=True),
        ),
    ]
